### ISSUE TITLE
Backend Error

### ISSUE THREAD

**Issue by vikas8669** [Zeeshu911/MERN-Stack-Hospital-Management-System-Web-Application#1]
Unable to start backend

**Comment by Zeeshu911** [comment]
First install node modules in your backend with npm i command and then run
this command: npm run dev

**Comment by songapradeepthi11** [comment]
unable to start backend can you tell me what are the commands that has to be used to run

**Comment by Aarav8400** [comment]
> unable to start backend can you tell me what are the commands that has to be used to run
npm install

**Comment by Zeeshu911** [comment]
Watch the tutorial. Or watch the last chapter of my Blogging Application tutorial where I explained that how you can download the code from github and run it in your own system.
